Vagrant.configure("2") do |config|
    config.vm.hostname = "s-ubuntu-2404"
    config.vm.box = "ubuntu/jammy64"
    config.ssh.forward_agent = true
    config.vm.network "public_network"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "s-ubuntu-2404"
        vb.gui = true
        vb.cpus = 4
        vb.memory = 8192
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
#         vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
        vb.customize ["modifyvm", :id, "--vram", "256"]
    end
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install git wget curl htop
    SHELL
end
