Vagrant.configure("2") do |config|
    config.vm.hostname = "s-ubuntu-2404"
    config.vm.box = "bento/ubuntu-24.04"
    config.ssh.forward_agent = true
    config.vm.network "private_network", type: "dhcp"

#     config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox" do |vb|
        vb.name = "s-ubuntu-2404"
#         vb.cpus = 2
#         vb.memory = 4192
#         vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
#         vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    end
#     config.vm.provision "shell", inline: <<-SHELL
#         apt-get update
#         apt-get install -y git wget curl htop
#     SHELL
end
