Vagrant.configure("2") do |config|
    config.vm.hostname = "d-ubuntu-2404"
    config.vm.box = "gusztavvargadr/ubuntu-desktop-2404-lts"
    config.ssh.forward_agent = true
    config.vm.provider "virtualbox" do |vb|
        vb.name = "d-ubuntu-2404"
        vb.gui = true
        vb.cpus = 4
        vb.memory = 8192
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
        vb.customize ["modifyvm", :id, "--vram", "256"]
        vb.customize ["setextradata", :id, "GUI/ScaleFactor", "1.5"]
        #vb.customize ["setextradata", :id, "CustomVideoMode1", "1920x1080x32"]
    end
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install git wget curl htop
    SHELL
end